import React, { useState } from 'react';
import { FileText, Upload, Printer, Copy, Sparkles } from 'lucide-react';
import { useGenerateTextNotes } from '@/hooks/useApi';
import { copyToClipboard, formatDateTime } from '@/utils';
import { useToast } from '@/hooks/use-toast';
import { Button } from '@/components/ui/button';

export function TextToNotes() {
  const [inputText, setInputText] = useState('');
  const [notes, setNotes] = useState('');
  
  const generateNotesMutation = useGenerateTextNotes();
  const { toast } = useToast();

  const handleGenerateNotes = async () => {
    if (!inputText.trim()) return;
    
    try {
      const result = await generateNotesMutation.mutateAsync(inputText);
      setNotes(result.content);
    } catch (error) {
      console.error('Failed to generate notes:', error);
    }
  };

  const handleCopyNotes = async () => {
    if (notes) {
      const success = await copyToClipboard(notes);
      if (success) {
        toast({
          title: 'Copied!',
          description: 'Notes copied to clipboard',
        });
      }
    }
  };

  const handlePrint = () => {
    if (!notes) return;
    
    const printContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Generated Notes</title>
          <style>
            body {
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
            }
            .header {
              text-align: center;
              border-bottom: 2px solid #3b82f6;
              padding-bottom: 20px;
              margin-bottom: 30px;
            }
            .header h1 {
              color: #3b82f6;
              margin: 0;
              font-size: 2.5em;
            }
            .content {
              white-space: pre-wrap;
              font-size: 14px;
              line-height: 1.8;
            }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e5e7eb;
              text-align: center;
              color: #6b7280;
              font-size: 12px;
            }
            @media print {
              body { margin: 0; padding: 15px; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Generated Notes</h1>
            <p>Generated on ${new Date().toLocaleString()}</p>
          </div>
          <div class="content">${notes}</div>
          <div class="footer">
            <p>Generated by NoteMate - AI-Powered Note Generation</p>
          </div>
        </body>
      </html>
    `;
    
    const printWindow = window.open('', '_blank');
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.focus();
    
    // Wait for content to load then print
    printWindow.onload = () => {
      printWindow.print();
      printWindow.close();
    };
    
    toast({
      title: 'Print Ready!',
      description: 'Print dialog opened. You can save as PDF from the print options.',
    });
  };

  return (
    <div className="min-h-screen py-8 sm:py-12 md:py-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-16">
          <div className="flex justify-center mb-8">
            <div className="p-4 bg-gradient-to-r from-blue-100 to-indigo-100 rounded-2xl shadow-lg">
              <FileText className="h-12 w-12 text-blue-600" />
            </div>
          </div>
          <h1 className="text-5xl sm:text-6xl font-bold text-gray-900 mb-6 leading-tight">
            Text to <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">Notes</span>
          </h1>
          <p className="text-xl sm:text-2xl text-gray-600 max-w-4xl mx-auto leading-relaxed font-medium">
            Transform any text into well-structured, easy-to-read notes instantly using advanced AI technology
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
          {/* Input Section */}
          <div className="bg-white rounded-2xl shadow-xl border border-slate-200 p-8">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold text-gray-900">Input Text</h2>
              <button className="flex items-center text-lg font-medium text-blue-600 hover:text-blue-700 transition-colors">
                <Upload className="h-5 w-5 mr-2" />
                Upload File
              </button>
            </div>
            
            <textarea
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder="Paste your text here or upload a document to get started..."
              className="w-full h-96 p-6 border-2 border-gray-200 rounded-xl resize-none focus:ring-4 focus:ring-blue-100 focus:border-blue-500 transition-all duration-300 bg-gray-50 text-gray-900 placeholder-gray-500 text-lg leading-relaxed"
            />
            
            <div className="flex items-center justify-between mt-6">
              <span className="text-lg text-gray-500 font-medium">
                {inputText.length} characters
              </span>
              <button
                onClick={handleGenerateNotes}
                disabled={!inputText.trim() || generateNotesMutation.isPending}
                className="flex items-center px-8 py-4 bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-semibold text-lg rounded-xl hover:from-blue-700 hover:to-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5"
              >
                {generateNotesMutation.isPending ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-3"></div>
                    Processing...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-5 w-5 mr-3" />
                    Generate Notes
                  </>
                )}
              </button>
            </div>
          </div>

          {/* Output Section */}
          <div className="bg-white rounded-2xl shadow-xl border border-slate-200 p-8">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold text-gray-900">Generated Notes</h2>
              {notes && (
                <div className="flex space-x-3">
                  <Button
                    onClick={handleCopyNotes}
                    variant="ghost"
                    size="sm"
                    className="text-blue-600 hover:text-blue-700 hover:bg-blue-50 font-medium text-lg px-4 py-2"
                  >
                    <Copy className="h-5 w-5 mr-2" />
                    Copy
                  </Button>
                  <Button
                    onClick={handlePrint}
                    variant="ghost"
                    size="sm"
                    className="text-green-600 hover:text-green-700 hover:bg-green-50 font-medium text-lg px-4 py-2"
                  >
                    <Printer className="h-5 w-5 mr-2" />
                    Print
                  </Button>
                </div>
              )}
            </div>
            
            <div className="h-96 p-6 border-2 border-gray-200 rounded-xl bg-gray-50 overflow-y-auto">
              {notes ? (
                <pre className="whitespace-pre-wrap text-lg text-gray-800 leading-relaxed">
                  {notes}
                </pre>
              ) : (
                <div className="flex items-center justify-center h-full text-gray-500">
                  <div className="text-center">
                    <FileText className="h-16 w-16 mx-auto mb-6 opacity-50" />
                    <p className="text-xl font-medium">Your generated notes will appear here</p>
                    <p className="text-lg mt-2">Enter text above and click Generate Notes to get started</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Features */}
        <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-10">
          <div className="text-center bg-white rounded-2xl p-8 shadow-lg border border-slate-200 hover:shadow-xl transition-shadow duration-300">
            <div className="flex justify-center mb-6">
              <div className="p-4 bg-gradient-to-r from-green-500 to-emerald-500 rounded-2xl shadow-lg">
                <Sparkles className="h-8 w-8 text-white" />
              </div>
            </div>
            <h3 className="text-2xl font-bold text-gray-900 mb-4">AI-Powered</h3>
            <p className="text-lg text-gray-600 leading-relaxed">Advanced AI algorithms extract key information and structure your notes intelligently</p>
          </div>
          
          <div className="text-center bg-white rounded-2xl p-8 shadow-lg border border-slate-200 hover:shadow-xl transition-shadow duration-300">
            <div className="flex justify-center mb-6">
              <div className="p-4 bg-gradient-to-r from-purple-500 to-indigo-500 rounded-2xl shadow-lg">
                <FileText className="h-8 w-8 text-white" />
              </div>
            </div>
            <h3 className="text-2xl font-bold text-gray-900 mb-4">Well-Structured</h3>
            <p className="text-lg text-gray-600 leading-relaxed">Automatically organized with headings, bullet points, and comprehensive summaries</p>
          </div>
          
          <div className="text-center bg-white rounded-2xl p-8 shadow-lg border border-slate-200 hover:shadow-xl transition-shadow duration-300">
            <div className="flex justify-center mb-6">
              <div className="p-4 bg-gradient-to-r from-orange-500 to-red-500 rounded-2xl shadow-lg">
                <Printer className="h-8 w-8 text-white" />
              </div>
            </div>
            <h3 className="text-2xl font-bold text-gray-900 mb-4">Export Ready</h3>
            <p className="text-lg text-gray-600 leading-relaxed">Download your notes in multiple formats for easy sharing and collaboration</p>
          </div>
        </div>
      </div>
    </div>
  );
}